### ISSUE TITLE
Error when executing test.py

### ISSUE THREAD

**Issue by natlouis** [amoudgl/pygoturn#17]
I completed training just fine, but I'm getting this error when I try to do evaluation:

```python
Traceback (most recent call last):
  File "src/test.py", line 121, in <module>
    main()
  File "src/test.py", line 118, in main
    tester.test()
  File "src/test.py", line 103, in test
    sample = self[i]
  File "src/test.py", line 59, in __getitem__
    sample = self.get_sample(idx)
  File "src/test.py", line 74, in get_sample
    prev_img = transform_prev({'image':prev, 'bb':prevbb})['image']
  File "/z/sw/packages/pytorch/py3.5/0.3.0/lib/python3.5/site-packages/torchvision-0.2.0-py3.5.egg/torchvision/transforms/transforms.py", line 42, in __call__
  File "/z/home/natlouis/pygoturn/src/helper.py", line 28, in __call__
    h, w = image.shape[:2]
ValueError: not enough values to unpack (expected 2, got 0)
```

It seems that when it's doing the transform: `CropPrev()` and then `Rescale()`, the `Rescale()` object gets a null image from sample. But when I reverse the order of the operations (scale and then crop), this error doesn't occur.

What are the supported versions of Pytorch & Python?
I'm using
* Python 3.5 
* Pytorch 0.3.0
* scipy 1.0.0
* scikit-image 0.13.1

**Comment by amoudgl** [comment]
Hi @natlouis, thanks for reporting the issue. I've fixed `test.py` script in my recent commits. Now, this repository supports python3 and pytorch 1.0. I'm closing this issue for now. Feel free to reopen if you get any errors.
